# Development stage
FROM node:21.7.3

WORKDIR /app

# Install Angular CLI globally
RUN npm install -g @angular/cli

# Copy package.json and package-lock.json
COPY client/package.json client/package-lock.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application
COPY client ./

# Expose port 4200 for ng serve
EXPOSE 4200

# The command will be specified in docker-compose.yml
CMD ["ng", "serve", "--host", "0.0.0.0", "--port", "4200", "--poll", "500"]