# Base stage
FROM node:21.7.3 AS base

WORKDIR /app

COPY client/package.json client/package-lock.json ./
RUN npm install

COPY client ./


# Test stage
FROM base AS test
# Runs tests
RUN npm test

# Development stage
FROM base AS dev

CMD ["npm", "start"]