# Base stage
FROM node:21.7.3 AS base

WORKDIR /app

COPY server/package.json server/package-lock.json ./
RUN npm install

COPY server ./

# Test stage
FROM base AS test

# Run tests
RUN npm test

# Final stage
FROM base AS final

# Expose the application port
EXPOSE 3000

# Start the application
CMD ["npx", "ts-node", "index.ts"]
