# Base stage
FROM node:22.4.1 AS base

WORKDIR /app

COPY server/package.json server/package-lock.json ./
RUN npm install

COPY server ./

RUN npm test

# Final stage
FROM base AS final

# Expose the application port
EXPOSE 3000