export enum EventID {
    VIEW_LANDING_PAGE = 'LANDING_PAGE',
    PLAY_TETRIS_IN_LANDING_PAGE = 'PLAY_TETRIS_IN_LANDING_PAGE',
    CLICK_LOGIN_FROM_LANDING_PAGE = 'LOGIN_FROM_LANDING_PAGE',
    CLICK_PLAY_AS_GUEST_FROM_LANDING_PAGE = 'PLAY_AS_GUEST_FROM_LANDING_PAGE',
    SUCCESSFUL_SIGNIN = 'SUCCESSFUL_SIGNIN',
    SIGNOUT = 'SIGNOUT',
    VIEW_PLAY_PAGE = 'VIEW_PLAY_PAGE',
    PLAY_SOLO_GAME = 'PLAY_SOLO_GAME',
    END_SOLO_GAME_BY_EXIT = 'END_SOLO_GAME_BY_EXIT',
    END_SOLO_GAME_BY_TOPOUT = 'END_SOLO_GAME_BY_TOPOUT',
    VIEW_FRIENDS_PAGE = 'VIEW_FRIENDS_PAGE',
    SEND_FRIEND_REQUEST = 'SEND_FRIEND_REQUEST',
    CANCEL_FRIEND_REQUEST = 'CANCEL_FRIEND_REQUEST',
    ACCEPT_FRIEND_REQUEST = 'ACCEPT_FRIEND_REQUEST',
    REJECT_FRIEND_REQUEST = 'REJECT_FRIEND_REQUEST',
    REMOVE_FRIEND = 'REMOVE_FRIEND',
    SEND_MATCH_CHALLENGE = 'SEND_MATCH_CHALLENGE',
    CANCEL_MATCH_CHALLENGE = 'CANCEL_MATCH_CHALLENGE',
    ACCEPT_MATCH_CHALLENGE = 'ACCEPT_MATCH_CHALLENGE',
    REJECT_MATCH_CHALLENGE = 'REJECT_MATCH_CHALLENGE',
    SEND_REMATCH_CHALLENGE = 'SEND_REMATCH_CHALLENGE',
    CANCEL_REMATCH_CHALLENGE = 'CANCEL_REMATCH_CHALLENGE',
    ACCEPT_REMATCH_CHALLENGE = 'ACCEPT_REMATCH_CHALLENGE',
    REJECT_REMATCH_CHALLENGE = 'REJECT_REMATCH_CHALLENGE',
    ABORT_MATCH = 'ABORT_MATCH',
    WIN_MATCH = 'WIN_MATCH',
    LOSE_MATCH = 'LOSE_MATCH',
    SPECTATE_PLAYER = 'SPECTATE_PLAYER',
    START_SETUP_OCR = 'START_SETUP_OCR',
    CANCEL_SETUP_OCR = 'CANCEL_SETUP_OCR',
    COMPLETE_SETUP_OCR = 'COMPLETE_SETUP_OCR',
    VIEW_PUZZLES_PAGE = 'VIEW_PUZZLES_PAGE',
    ATTEMPT_PUZZLE = 'ATTEMPT_PUZZLE',
    SOLVE_PUZZLE_CORRECTLY = 'SOLVE_PUZZLE_CORRECTLY',
    SOLVE_PUZZLE_INCORRECTLY = 'SOLVE_PUZZLE_INCORRECTLY',
    EXIT_PUZZLE = 'EXIT_PUZZLE',
}

/**
 * An event is a user-triggered action that is captured by the system and useful for web analytics.
 */
export interface Event {
    userid: string | null;
    sessionid: string;
    event: EventID;
}